### ISSUE TITLE
failed to locate @import file ~quasar-variables.styl

### ISSUE THREAD

**Issue by ymoreiratiti** [baggachipz/q-form-builder#1]
Steps:
1. Create a new project with quasar 1.0.0
2. Replace MyLayout.vue with
```vue
<template>
  <q-layout view="lHh Lpr lFf">
    <q-page-container>
      Start
      <q-form-builder v-model="myForm" />
      End
    </q-page-container>
  </q-layout>
</template>

<script>
import QFormBuilder from 'q-form-builder'

export default {
  name: 'MyApp',
  components: {
    QFormBuilder
  },
  data: function () {
    return {
      myForm: []
    }
  }
}
</script>
```

```shell
Failed to compile.

./node_modules/q-form-builder/src/components/QFormBuilder.vue?vue&type=style&index=0&id=5590e2fa&scoped=true&lang=stylus& (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-2-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-oneOf-2-2!./node_modules/stylus-loader??ref--6-oneOf-2-3!./node_modules/@quasar/app/lib/webpack/loader.quasar-stylus-variables.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/q-form-builder/src/components/QFormBuilder.vue?vue&type=style&index=0&id=5590e2fa&scoped=true&lang=stylus&)
Module build failed (from ./node_modules/stylus-loader/index.js):
  Error: C:\temp\teste\node_modules\q-form-builder\src\components\QFormBuilder.vue:187:9
     183| 
     184| <style scoped lang="stylus">
     185|   @import '~quasar-variables'
     186| 
     187|   .q-btn.source-field
  ----------------^
     188|     width 129px
     189|     margin 0px 2px 5px 2px
     190| 
  failed to locate @import file ~quasar-variables.styl
  
  - evaluator.js:157 CachedPathEvaluator.visitImport
    [teste]/[stylus-loader]/lib/evaluator.js:157:21
  
  - index.js:28 CachedPathEvaluator.Visitor.visit
    [teste]/[stylus]/lib/visitor/index.js:28:40
  
  - evaluator.js:160 CachedPathEvaluator.Evaluator.visit
    [teste]/[stylus]/lib/visitor/evaluator.js:160:18
  
  - evaluator.js:707 CachedPathEvaluator.Evaluator.visitRoot
    [teste]/[stylus]/lib/visitor/evaluator.js:707:27
  
  - index.js:28 CachedPathEvaluator.Visitor.visit
    [teste]/[stylus]/lib/visitor/index.js:28:40
  
  - evaluator.js:160 CachedPathEvaluator.Evaluator.visit
    [teste]/[stylus]/lib/visitor/evaluator.js:160:18
  
  - evaluator.js:247 CachedPathEvaluator.Evaluator.evaluate
    [teste]/[stylus]/lib/visitor/evaluator.js:247:15
  
  - renderer.js:86 Renderer.render
    [teste]/[stylus]/lib/renderer.js:86:26
  
  - index.js:167 
    [teste]/[stylus-loader]/index.js:167:12
  
  - makePromise.js:840 tryCatchReject
    [teste]/[when]/lib/makePromise.js:840:30
  
  - makePromise.js:799 runContinuation1
    [teste]/[when]/lib/makePromise.js:799:4
  
  - makePromise.js:590 Fulfilled.when
    [teste]/[when]/lib/makePromise.js:590:4
  
  - makePromise.js:481 Pending.run
    [teste]/[when]/lib/makePromise.js:481:13
  
  - Scheduler.js:62 Scheduler._drain
    [teste]/[when]/lib/Scheduler.js:62:19
  
  - Scheduler.js:27 Scheduler.drain
    [teste]/[when]/lib/Scheduler.js:27:9
  
  - next_tick.js:172 process._tickCallback
    internal/process/next_tick.js:172:11  
```

**Quasar Info**

```shell
Operating System - Windows_NT(10.0.17134) - win32/x64
NodeJs - 10.0.0

Global packages
  NPM - 6.9.2
  yarn - 1.9.4
  @quasar/cli - 1.0.0
  cordova - 9.0.0

Important local packages
  quasar - 1.0.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.2 -- Quasar Framework local CLI
  @quasar/extras - 1.1.4 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.0 -- Babel compiler core.
  webpack - 4.34.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - DU1792
  vEthernet (Opção Padrão) - 172.29.140.97
  vEthernet (Internet) - 192.168.1.111
```

**Comment by baggachipz** [comment]
I'll look into this; I plan on updating the package to use v1.x (instead of just beta releases) very soon. Also many updates coming.

**Comment by cristoferdomingues** [comment]
Any news about this issue?

**Comment by baggachipz** [comment]
I have fixed this issue now; however, I'm having a hard time getting this component to publish on npm and be usable as a library rather than a global component. If anyone has any ideas, please make some changes and file a PR.

**Comment by tarkhil** [comment]
Problem persists. I suppose quasar init should give me something running...

**Comment by yaronveg** [comment]
Same issue here
